#服务器配置
server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
#spring 配置
spring: 
   #模板
    thymeleaf:
       prefix: classpath:/templates/
       suffix: .html
       mode: HTML5
       encoding: UTF-8
       content-type: text/html
       cache: false
    #数据源
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/yeqiu
      username: root
      password: lc908752
      driver-class-name: com.mysql.jdbc.Driver
    redis:
       host: 127.0.0.1
       port: 6379
       password: lc908752
       database: 0
mybatis:
   mapperLocations: classpath:yeqiu/springboot/*/mapper/*.xml
   
